const upperMarquee = [
    "/01.svg",
    "/02.svg",
    "/03.svg",
    "/04.svg",
    "/05.svg",
    "/06.svg",
    "/07.svg",
    "/08.svg",
    "/09.svg",
    "/10.svg",
    "/11.svg",
  ];

  const lowerMarquee = [
    "/12.svg",
    "/13.svg",
    "/14.svg",
    "/15.svg",
    "/16.svg",
    "/17.svg",
    "/18.svg",
    "/19.svg",
    "/20.svg",
    "/21.svg",
    "/22.svg",
  ];

  const tags = [
    "Software Engineer",
    "Data Scientist",
    "Product Manager",
    "UX Designer",
    "Marketing Specialist",
    "Financial Analyst",
    "HR Coordinator",
    "Sales Representative",
    "Graphic Designer",
    "Customer Manager",
  ];

  const carouselImages = [
    'page1-images/01.png',
    'page1-images/02.png',
    'page1-images/03.png',
  ]

  const jobTitles = [
    "Accountant",
    "Actor",
    "Actuary",
    "Advertising Manager",
    "Aerospace Engineer",
    "Agricultural Engineer",
    "Air Traffic Controller",
    "Aircraft Mechanic",
    "Architect",
    "Art Director",
    "Artist",
    "Astronomer",
    "Athletic Trainer",
    "Attorney",
    "Auditor",
    "Author",
    "Baker",
    "Bank Teller",
    "Barber",
    "Bartender",
    "Biochemist",
    "Biologist",
    "Biomedical Engineer",
    "Bookkeeper",
    "Business Analyst",
    "Butcher",
    "Carpenter",
    "Cartographer",
    "Cashier",
    "Chef",
    "Chemical Engineer",
    "Chemist",
    "Chiropractor",
    "Civil Engineer",
    "Clergy",
    "Coach",
    "Computer Programmer",
    "Computer Support Specialist",
    "Construction Manager",
    "Copywriter",
    "Correctional Officer",
    "Cost Estimator",
    "Court Reporter",
    "Customer Service Representative",
    "Data Analyst",
    "Dental Assistant",
    "Dentist",
    "Designer",
    "Dietitian",
    "Doctor",
    "Economist",
    "Editor",
    "Electrician",
    "Elementary School Teacher",
    "Engineer",
    "Environmental Scientist",
    "Event Planner",
    "Executive Assistant",
    "Farmer",
    "Fashion Designer",
    "Film Director",
    "Financial Analyst",
    "Firefighter",
    "Fitness Trainer",
    "Florist",
    "Graphic Designer",
    "Hairdresser",
    "Healthcare Administrator",
    "Human Resources Specialist",
    "Industrial Engineer",
    "Information Security Analyst",
    "Insurance Agent",
    "Interpreter",
    "IT Manager",
    "Journalist",
    "Judge",
    "Lab Technician",
    "Lawyer",
    "Librarian",
    "Logistician",
    "Machinist",
    "Marketing Manager",
    "Massage Therapist",
    "Mechanical Engineer",
    "Medical Assistant",
    "Microbiologist",
    "Nurse",
    "Nutritionist",
    "Occupational Therapist",
    "Office Manager",
    "Optometrist",
    "Painter",
    "Paralegal",
    "Pharmacist",
    "Photographer",
    "Physical Therapist",
    "Pilot",
    "Plumber",
    "Police Officer",
    "Project Manager",
    "Psychologist",
    "Public Relations Specialist",
    "Real Estate Agent",
    "Receptionist",
    "Research Scientist",
    "Sales Manager",
    "Software Developer",
    "Statistician",
    "Surgeon",
    "Teacher",
    "Therapist",
    "Translator",
    "Veterinarian",
    "Web Developer",
    "Writer",
    "Software Engineer",
    "Data Scientist",
    "Product Manager",
    "UX Designer",
    "Marketing Specialist",
    "Financial Analyst",
    "HR Coordinator",
    "Sales Representative",
    "Graphic Designer",
    "Customer Manager",
];


  export { upperMarquee, lowerMarquee, tags, carouselImages, jobTitles };